[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/api/auth/login/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
DJANGO_SETTINGS_MODULE = "config.settings.production"
